class Constant {
  // Backend & frontend base URLs
  // NOTE: For local development you can temporarily switch these back to 10.0.2.2 or your LAN IP.
  static const String shareLink = 'https://buyingat.com'; // Frontend URL
  static const String baseUrl = 'https://buyingat.com';   // Backend host (API prefix added via subUrl)

  static const String subUrl = '/api'; // API prefix, combined with baseUrl in main.dart
  static const String imageBaseUrl = '$baseUrl/storage/';
  static const String bannersUrl = '/home/sliders';
  static const String categoriesUrl = '/home/categories';
  static const String bestDealsUrl = '/home/best-deals';
  static const String featuredProductsUrl = '/home/featured-products';
  static const String electronicsAccessoriesUrl = '/home/electronics-accessories';
  static const String topRatedUrl = '/home/top-rated';
  static const String newArrivalsUrl = '/home/new-arrivals';
  static const String advertiseUrl = '/home/advertise';
  static const String manualLoginUrl = '/home/login';
  static const String manualSignUpUrl = '/home/signup';
  static const String googleLoginUrl = "/google-login/create-user";
  static const String sendResetOtpUrl = '/home/send-reset-otp';
  static const String verifyOtpUrl = '/home/verify-otp';
  static const String resetPasswordUrl = '/home/reset-password';
  static const String getUserUrl = '/user/get_me';
  static const String fetchBillingUrl = '/user/billing-address';
  static const String fetchShippingUrl = '/user/shipping-address';
  static const String gatewayUrl = '/user/get-all-from-frontend';
  static const String sslCommerceUrl = '/user/sslcommerz/pay';
  static const String paypalPaymentUrl = '/user/paypal/initiate-payment';
  static const String stripePaymentUrl = '/user/stripe/create-checkout-session';
  static const String razorpayUrl = '/user/razorpay/payment';
  static const String razorpayPayUrl = "/user/razorpay/pay";
  static const String getTransactionsUrl = "/user/get-transactions";
  static const String countriesUrl = "/home/countries";
  static const String citiesUrl = "/home/cities";
  static const String updateMeUrl = "/user/update_me";
  static const String changePasswordUrl = "/user/change_password";
  static const String shopUrl = "/user/shops";
  static const String shopUpdateUrl = "/user/shops/update";
  static const String ticketsUrl = "/user/tickets";
  static const String packagesUrl = "/home/packages";
  static const String subscribeUrl = "/user/subscribe";
  static const String myProductsUrl = "/user/products-by-vendor";
  static const String unPublishPropertyUrl = "/user/product/unpublish";
  static const String deletePropertyUrl = "/user/products";
  static const String customerOrderUrl = "/user/vendor-or-user-order-list";
  static const String myOrderUrl = "/user/user-order-list";
  static const String userOrderDataUrl = "/user/user-order-data";
  static const String orderDetailsUrl = "/user/order-details";
  static const String updateOrderStatusUrl = "/user/update-order-status";
  // Pay for an existing order using wallet: /user/order/{id}/pay-with-wallet
  static const String payWithWalletBaseUrl = "/user/order";
  static const String createMsgUrl = "/user/message";
  static const String getMsgUrl = "/user/get-message";
  static const String getAllMsgThreadUrl = "/user/conversation-threads/get-all";
  static const String createMsgThreadUrl = "/user/conversation-thread";
  static const String singleProductUrl = "/home/products";
  static const String brandUrl = "/home/brands";
  static const String storeProductUrl = "/user/products";
  static const String editProductUrl = "/user/edit-product";
  static const String replayTicketUrl = "/customer/messages";
  static const String viewSupportMsgUrl = "/user/ticket-messages";
  static const String deleteSupportTicket = "/customer/close-tickets";
  static const String filterUrl = "/home/products/filter";
  static const String sendReportUrl = "/user/reports";
  static const String cartItemsUrl = "/user/get-cart-items";
  static const String addToCardUrl = "/user/add-to-cart";
  static const String buyNowUrl = "/user/buy-now";
  static const String cartDetailsUrl = "/user/cart-details";
  static const String clearAllCartUrl = "/user/clear-cart-items";
  static const String increaseCartCountUrl = "/user/increase-cart-count";
  static const String decreaseCartCountUrl = "/user/decrease-cart-count";
  static const String removeSingleCartItemUrl = "/user/remove-cart-item";
  static const String orderFromCartUrl = "/user/order-from-cart";
  static const String fetchWishListUrl = "/user/product/wishlists";
  static const String deleteWishListUrl = "/user/product/wishlists";
  static const String addToWishListUrl = "/user/product/wishlists";
  static const String boostUrl = "/user/features";
  static const String morePagesUrl = "/home/more-pages";
  static const String stockManageUrl = "/user/product-stocks-multiple";
  static const String userProfileUrl = "/user-profile";
  static const String browseCardsUrl = "/home/cards/filter";
  static const String sellerInventoryUrl = "/seller-inventory";
  static const String buyerProfilesUrl = "/buyer-profiles";
  static const String buyerProfileUrl = "/buyer-profile";
  static const String promotionsUrl = "/promotions";
  static const String userStatusUrl = "/user/status/user";
  static const String userStatusOnlineUrl = "/user/status/online";
  static const String userStatusOfflineUrl = "/user/status/offline";
  static const String userStatusLastSeenUrl = "/user/status/last-seen";

  static const String fontFamilyClash = 'ClashDisplay';
}
